### ISSUE TITLE
bug report even_odd_site.java

### ISSUE THREAD

**Issue by adhinkel** [BenQuack/GORLS#21]
code has one compiler error and one logic error.

Expected behavior: adds even numbers to even column of table and odd numbers to odd column.

Actual behavior: the code would not run

line 7: equality comparison operator '==' used in place of assignment operator '='.
line 15: / operator is used instead of %. this yields the incorrect answers

**Comment by cbutera15** [comment]
fixed both errors in lines 7 and 15.
