### ISSUE TITLE
Missing 'r' at the end of variable name

### ISSUE THREAD

**Issue by cbutera15** [BenQuack/GORLS#23]
https://github.com/BenQuack/GORLS/blob/0ad96ad921df6843ee340dae5e59c16451e629b3/programming%20files/datetime_convert.java#L14

## Description:
Missing single 'r' at the end of the variable name at the end of line 14 to change formatte to formatter. 

## Solution
Add 'r' at the end of the variable name in line 14.

**Comment by BenQuack** [comment]
Fixed Colins mistake on line 14 formatte -> formatter
