### ISSUE TITLE
Missing semicolons

### ISSUE THREAD

**Issue by David-Poulin** [BenQuack/GORLS#24]
Description 
 No semicolons in lines 8, 9 and 11 of remove_duplicates.cc
Steps to reproduce
1. Always a bug because no semicolon

Expected behavior
 compiling

Actual Behavior:
 Not compiling

Additional info:
 Windows
 Chrome

**Comment by AlexaWitkin** [comment]
Added semicolons to lines 8, 9, and 11. Bug = fixed.
