### ISSUE TITLE
Even_odd_site.cc For Loop Issue 

### ISSUE THREAD

**Issue by jboothho** [BenQuack/GORLS#25]
The file name in line 7 is incorrect and will result in an error opening the file. The for loop will also not properly run due to a syntax error in the first line. 

<img width="239" alt="Screenshot 2024-04-11 at 5 22 29 PM" src="https://github.com/BenQuack/GORLS/assets/143525406/599eb713-3fce-48a1-afd9-12f6b5304830">

I recommend fixing the file name at the top to allow for successful opening and reading
I recommend adding an additional + in the for loop declaration to allow for successful looping

This bug is HIGH PRIORITY and CRITICAL!

This bug is HIGHLY AN ISSUE !

**Comment by jlemahieu03** [comment]
Changed fileIn to file to make the variable name change to make for successful file opened as well as fixed the syntax error.
